// Imports
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import {useRouter} from 'next/router'
import {useEffect} from 'react'
import Fade from 'react-reveal/Fade'


// Main Function
const Home = () => {

  const router = useRouter();

  useEffect(() => {
    // setTimeout(() => {
      router.push('/home')
    // }, 5000);
  }, []);

  return (
    <div>
      <Head>
        <title>Ad Link</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='w-full h-screen relative flex align-middle justify-center'>
        <div className='w-full h-full top-0 left-0 absolute overflow-hidden z-[-1]'>
          <video className='w-full h-full object-cover' autoPlay loop muted src="/Videos/Intro.mp4" type="video/mp4"/>
        </div>
        <div className='w-full h-full bg-[#000000ba] flex text-white flex-col pt-10 pl-20'>
          <Fade top>
            <Image src='/Images/Logo.png' width={250} height={100}/>
          </Fade>
          <Fade left>
            <div className='w-2/6 h-3/6 bg-black m-auto'>
              Text
            </div>
          </Fade>
          <Link href='/home'>Skip</Link>
        </div>
      </div>
    </div>
  )
}


// Export
export default Home;